---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: fluentd