kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
  namespace: webapp-prod
data:
  config.toml: |-
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
        minVersion = "VersionTLS12"
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        ]
    [acme]
    email = "andrej.turk91@gmail.com"
    storage = "acme.json"
    entryPoint = "https"
    onHostRule = true
    [[acme.domains]]
      main = "webapp.gulzoo.eu"
    [acme.httpChallenge]
    entryPoint = "http"