---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: webapp-prod
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: webapp-prod
spec:
  selector:
    app: traefik-ingress-lb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
